# Kolhapur Theme — Hyprland

general {
    col.active_border = rgba(C98A2Cee) rgba(7B2323ee) 45deg
    col.inactive_border = rgba(2E1F18aa)
    border_size = 2
    gaps_in = 4
    gaps_out = 10
    layout = dwindle
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.92

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(1C1210cc)
    }

    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        contrast = 1.05
        brightness = 1.0
    }
}

misc {
    background_color = rgb(1C1210)
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
